spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
      dialect.H2Dialect: org.hibernate.dialect.H2Dialect
    datasource:
        url: jdbc:h2:mem:testdb
        username: sa
